# ===========================================
# DEPLOYMENT - LMS PLATFORM
# ===========================================
# Deployment principal de la aplicación LMS

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-platform-deployment
  namespace: lms-platform
  labels:
    app: lms-platform
    component: backend
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lms-platform
      component: backend
  template:
    metadata:
      labels:
        app: lms-platform
        component: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: lms-platform-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: lms-platform
        image: gcr.io/ai-academy-461719/lms-platform:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: lms-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: lms-config
              key: PORT
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            configMapKeyRef:
              name: lms-config
              key: NEXT_PUBLIC_APP_URL
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: lms-config
              key: GOOGLE_CLOUD_PROJECT_ID
        - name: GOOGLE_CLOUD_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: lms-config
              key: GOOGLE_CLOUD_BUCKET_NAME
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: DATABASE_URL
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: CLERK_SECRET_KEY
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: STRIPE_API_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: MUX_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: MUX_TOKEN_ID
        - name: MUX_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: MUX_TOKEN_SECRET
        - name: UPLOADTHING_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: UPLOADTHING_SECRET
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: google-credentials
          mountPath: /app/credentials
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
      volumes:
      - name: google-credentials
        persistentVolumeClaim:
          claimName: google-credentials-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - lms-platform
              topologyKey: kubernetes.io/hostname
---
# ===========================================
# HORIZONTAL POD AUTOSCALER
# ===========================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lms-platform-hpa
  namespace: lms-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lms-platform-deployment
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
